#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
controllers:
    resource: ../src/Action/
    type: annotation
api_login_check:
    path: /login
